v {xschem version=3.4.6 file_version=1.2}
G {}
K {}
V {}
S {}
E {}
T {4uA} -720 -30 0 0 0.4 0.4 {}
T {250nA} -1130 -530 0 0 0.4 0.4 {}
T {250nA} -1150 -30 0 0 0.4 0.4 {}
T {500nA} -220 -530 0 0 0.4 0.4 {}
T {500nA} -210 -20 0 0 0.4 0.4 {}
T {mirror 1:16} -1170 0 0 0 0.4 0.4 {}
T {mirror 1:1} -1160 -590 0 0 0.4 0.4 {}
T {Level shifters (1.2V to 3.3V)} -2150 -980 0 0 0.4 0.4 {}
T {1uA} -230 -700 0 0 0.4 0.4 {}
T {Pbias can only be generated by one source (bias_amp or bias_pstack)
depending on the value of ena_vbg_3v3.  Use this only for current
sources (current sinks are still related to the avdd-referenced bias).} -1040 -1530 0 0 0.5 0.5 {}
T {Bias generator front-end} -2160 -1220 0 0 0.6 0.6 {}
T {The source and sink testpoints form the beginning of the backend
bias current chain and may be used as dummy devices.} -370 70 0 0 0.5 0.5 {}
T {This section self-biases based on a resistor.  It will run the
bias generator but is not as stable as using the bandgap
reference.  Note that current sinks do not use a bandgap-
referenced bias voltage, only current sources.} -1590 60 0 0 0.5 0.5 {}
T {Note: cap is a metal fingered cap.} -880 -920 0 0 0.4 0.4 {}
T {The "fine" setting reduces the source unit bias from 250nA to 50nA (factor of 5 reduction).
The "coarse" setting increases the source unit bias from 250nA to 1uA (factor of 4 increase).
The settings do not change the sink unit bias.
All currents listed in the schematic are for the coarse setting (250nA per unit bias)} -2440 -1100 0 0 0.3 0.3 {}
T {When bandgap-stabilized, the current reference can be set to three scales:
1) Coarse:  Each current unit is 1uA
2) Standard:  Each current unit is 250nA
3) Fine:  Each current unit is 50nA} -760 -1410 0 0 0.3 0.3 {}
T {dummy stacks.  Note that the itail pin is
connected to other nets, but the dummy stacks
are disabled, so they contribute no current.} 80 -290 0 0 0.3 0.3 {}
N -420 -410 -420 -380 {
lab=ref_in}
N -530 -160 -420 -160 {
lab=nset}
N -870 -160 -830 -160 {
lab=ena_3v3}
N -870 -220 -870 -160 {
lab=ena_3v3}
N -970 -160 -930 -160 {
lab=#net1}
N -1280 -450 -1280 -410 {
lab=pbias}
N -1310 -470 -1310 -390 {
lab=pcasc}
N -1310 -390 -1280 -390 {
lab=pcasc}
N -330 -450 -330 -400 {
lab=pbias}
N -360 -380 -330 -380 {
lab=pcasc}
N -360 -470 -360 -380 {
lab=pcasc}
N -330 -360 -330 -300 {
lab=enb_test0_3v3}
N -330 -210 -330 -160 {
lab=ena_test0_3v3}
N -30 -200 -30 -160 {
lab=snk_test0}
N -2510 -320 -2490 -320 {
lab=ena_snk_test0}
N -2510 -390 -2490 -390 {
lab=ena_src_test0}
N -1070 -900 -940 -900 {
lab=nbias}
N -560 -1100 -500 -1100 {
lab=enb_std_3v3}
N -2510 -480 -2490 -480 {
lab=ena}
N -1040 -1070 -1010 -1070 {
lab=vfb}
N -1080 -1110 -1020 -1110 {
lab=ena_vbg_3v3}
N -1340 -660 -1300 -660 {
lab=dvdd}
N -1340 -630 -1300 -630 {
lab=dvss}
N -170 -790 -170 -730 {
lab=avss}
N -170 -960 -170 -940 {
lab=vfb}
N -710 -450 -330 -450 {
lab=pbias}
N -980 -410 -950 -410 {
lab=avdd}
N -530 -490 -30 -490 {
lab=avdd}
N -2130 -320 -1830 -320 {
lab=ena_test0_3v3}
N -2130 -480 -1830 -480 {
lab=ena_3v3}
N -2190 -150 -2150 -150 {
lab=ref_sel_vbg}
N -2190 -110 -2150 -110 {
lab=ena}
N -2190 -70 -2150 -70 {
lab=ena_src_test0}
N -2190 -30 -2150 -30 {
lab=ena_snk_test0}
N -1290 -1150 -1010 -1150 {
lab=vbg}
N -2130 -390 -1830 -390 {lab=enb_test0_3v3}
N -2240 -550 -2160 -550 {lab=#net2}
N -2410 -480 -2280 -480 {lab=#net3}
N -2410 -390 -2370 -390 {lab=#net4}
N -2370 -390 -2370 -370 {lab=#net4}
N -2370 -370 -2280 -370 {lab=#net4}
N -2410 -320 -2280 -320 {lab=#net5}
N -2550 -550 -2510 -550 {
lab=ref_sel_vbg}
N -2510 -480 -2510 -450 {lab=ena}
N -2550 -480 -2510 -480 {
lab=ena}
N -2510 -450 -2350 -450 {lab=ena}
N -2350 -460 -2350 -450 {lab=ena}
N -2350 -460 -2280 -460 {lab=ena}
N -2510 -320 -2510 -280 {lab=ena_snk_test0}
N -2550 -320 -2510 -320 {
lab=ena_snk_test0}
N -2510 -280 -2340 -280 {lab=ena_snk_test0}
N -2340 -300 -2340 -280 {lab=ena_snk_test0}
N -2340 -300 -2280 -300 {lab=ena_snk_test0}
N -2510 -430 -2510 -390 {lab=ena_src_test0}
N -2550 -390 -2510 -390 {
lab=ena_src_test0}
N -2510 -430 -2340 -430 {lab=ena_src_test0}
N -2340 -430 -2340 -390 {lab=ena_src_test0}
N -2340 -390 -2280 -390 {lab=ena_src_test0}
N -350 -140 -330 -140 {lab=nbias}
N -350 -140 -350 -80 {lab=nbias}
N -860 -80 -350 -80 {
lab=nbias}
N -860 -140 -830 -140 {lab=nbias}
N -860 -140 -860 -80 {lab=nbias}
N -530 -40 -30 -40 {
lab=avss}
N -1330 -40 -970 -40 {
lab=avss}
N -330 -120 -330 -60 {lab=ncasc}
N -830 -60 -330 -60 {lab=ncasc}
N -830 -120 -830 -60 {lab=ncasc}
N -1290 -120 -1290 -60 {lab=ncasc}
N -30 -360 -30 -280 {lab=src_test0}
N -980 -370 -930 -370 {lab=#net6}
N -930 -320 -930 -300 {lab=#net6}
N -930 -240 -930 -160 {lab=#net1}
N -420 -220 -420 -160 {lab=nset}
N -420 -320 -420 -280 {lab=#net7}
N -560 -410 -530 -410 {lab=avdd}
N -690 -490 -530 -490 {
lab=avdd}
N -560 -370 -530 -370 {lab=#net6}
N -530 -370 -530 -320 {lab=#net6}
N -930 -320 -530 -320 {lab=#net6}
N -930 -370 -930 -320 {lab=#net6}
N -920 -470 -920 -390 {lab=pcasc}
N -920 -470 -360 -470 {
lab=pcasc}
N -1310 -470 -920 -470 {
lab=pcasc}
N -920 -390 -860 -390 {lab=pcasc}
N -880 -370 -860 -370 {lab=enb_vbg_3v3}
N -880 -370 -880 -280 {lab=enb_vbg_3v3}
N -880 -280 -850 -280 {lab=enb_vbg_3v3}
N -870 -220 -840 -220 {lab=ena_3v3}
N -1380 -370 -1280 -370 {lab=ena_vbg_3v3}
N -1330 -160 -1270 -160 {lab=ena_3v3}
N -1370 -490 -950 -490 {
lab=avdd}
N -560 -1120 -500 -1120 {lab=pcasc}
N -830 -1110 -830 -1070 {lab=pbias}
N -850 -1110 -830 -1110 {
lab=pbias}
N -560 -1230 -500 -1230 {lab=pcasc}
N -700 -1250 -500 -1250 {lab=pbias}
N -830 -1110 -700 -1110 {
lab=pbias}
N -560 -1210 -500 -1210 {lab=enb_fine_3v3}
N -2100 -810 -2080 -810 {lab=#net8}
N -2000 -810 -1920 -810 {lab=#net9}
N -2100 -810 -2100 -770 {lab=#net8}
N -2100 -770 -1970 -770 {lab=#net8}
N -1970 -790 -1970 -770 {lab=#net8}
N -1970 -790 -1920 -790 {lab=#net8}
N -1290 -730 -920 -730 {
lab=avss}
N -920 -1060 -920 -730 {lab=avss}
N -170 -880 -170 -850 {lab=#net10}
N -940 -1030 -940 -900 {lab=nbias}
N -830 -1010 -830 -960 {lab=vfb}
N -1040 -960 -830 -960 {
lab=vfb}
N -1040 -1070 -1040 -960 {lab=vfb}
N -920 -730 -170 -730 {lab=avss}
N -830 -960 -170 -960 {lab=vfb}
N -170 -990 -170 -960 {lab=vfb}
N -200 -990 -170 -990 {lab=vfb}
N -200 -1030 -140 -1030 {lab=avdd}
N -560 -1010 -500 -1010 {lab=pcasc}
N -700 -1030 -500 -1030 {lab=pbias}
N -700 -1110 -700 -1030 {lab=pbias}
N -560 -990 -500 -990 {
lab=enb_coarse_3v3}
N -970 -40 -530 -40 {
lab=avss}
N -1310 -140 -1310 -80 {lab=nbias}
N -1290 -120 -1270 -120 {lab=ncasc}
N -1310 -140 -1270 -140 {lab=nbias}
N -1310 -80 -860 -80 {lab=nbias}
N -1290 -60 -830 -60 {lab=ncasc}
N -2510 -890 -2480 -890 {lab=ref_sel_fine}
N -2100 -910 -2080 -910 {lab=#net11}
N -2000 -910 -1920 -910 {lab=#net12}
N -2100 -910 -2100 -870 {lab=#net11}
N -2100 -870 -1970 -870 {lab=#net11}
N -1970 -890 -1970 -870 {lab=#net11}
N -1970 -890 -1920 -890 {lab=#net11}
N -2010 -620 -1830 -620 {lab=enb_vbg_3v3}
N -2010 -550 -1830 -550 {lab=ena_vbg_3v3}
N -2510 -550 -2370 -550 {lab=ref_sel_vbg}
N -2510 -620 -2510 -550 {lab=ref_sel_vbg}
N -2240 -600 -2160 -600 {lab=#net2}
N -2240 -600 -2240 -550 {lab=#net2}
N -2290 -550 -2240 -550 {lab=#net2}
N -2210 -530 -2160 -530 {lab=ref_sel_vbg}
N -2210 -620 -2210 -530 {lab=ref_sel_vbg}
N -2210 -620 -2160 -620 {lab=ref_sel_vbg}
N -2240 -620 -2210 -620 {lab=ref_sel_vbg}
N -2100 -710 -2080 -710 {lab=#net13}
N -2000 -710 -1920 -710 {lab=#net14}
N -2100 -710 -2100 -670 {lab=#net13}
N -2100 -670 -1970 -670 {lab=#net13}
N -1970 -690 -1970 -670 {lab=#net13}
N -1970 -690 -1920 -690 {lab=#net13}
N -1770 -710 -1750 -710 {lab=enb_std_3v3}
N -1770 -810 -1750 -810 {lab=enb_fine_3v3}
N -1770 -910 -1750 -910 {lab=enb_coarse_3v3}
N -2240 -890 -2220 -890 {lab=ref_sel_vbg}
N -2240 -790 -2220 -790 {lab=ref_sel_vbg}
N -2240 -890 -2240 -790 {lab=ref_sel_vbg}
N -2240 -690 -2220 -690 {lab=ref_sel_vbg}
N -2240 -790 -2240 -690 {lab=ref_sel_vbg}
N -2360 -910 -2300 -910 {lab=#net15}
N -2300 -930 -2300 -910 {lab=#net15}
N -2300 -930 -2220 -930 {lab=#net15}
N -2550 -810 -2510 -810 {lab=ref_sel_fine}
N -2510 -890 -2510 -810 {lab=ref_sel_fine}
N -2530 -930 -2480 -930 {lab=ref_sel_coarse}
N -2260 -830 -2220 -830 {lab=#net16}
N -2280 -730 -2220 -730 {lab=#net17}
N -2530 -850 -2530 -710 {lab=ref_sel_coarse}
N -2550 -930 -2530 -930 {lab=ref_sel_coarse}
N -2530 -710 -2400 -710 {lab=ref_sel_coarse}
N -2510 -810 -2490 -810 {lab=ref_sel_fine}
N -2410 -810 -2380 -810 {lab=#net18}
N -2410 -810 -2410 -750 {lab=#net18}
N -2410 -750 -2400 -750 {lab=#net18}
N -2530 -850 -2380 -850 {lab=ref_sel_coarse}
N -2530 -930 -2530 -850 {lab=ref_sel_coarse}
N -2240 -690 -2240 -620 {lab=ref_sel_vbg}
N -2510 -620 -2240 -620 {lab=ref_sel_vbg}
N -890 -410 -860 -410 {lab=dummypbias}
N -890 -440 -890 -410 {lab=dummypbias}
N -890 -440 -880 -440 {lab=dummypbias}
N -30 -40 420 -40 {lab=avss}
N 400 -120 420 -120 {lab=avss}
N 400 -160 440 -160 {lab=nset}
N 270 -490 420 -490 {lab=avdd}
N 400 -400 420 -400 {lab=avdd}
N 400 -360 430 -360 {lab=vfb}
N 50 -380 100 -380 {lab=pcasc}
N 50 -470 50 -380 {lab=pcasc}
N -360 -470 50 -470 {
lab=pcasc}
N 70 -360 100 -360 {lab=avdd}
N 70 -160 100 -160 {lab=avss}
N 80 -140 100 -140 {lab=nbias}
N 80 -140 80 -80 {lab=nbias}
N -350 -80 80 -80 {
lab=nbias}
N 100 -120 100 -60 {lab=ncasc}
N -330 -60 100 -60 {lab=ncasc}
N 80 -400 100 -400 {lab=dummypbias}
N 80 -430 80 -400 {lab=dummypbias}
N 80 -430 100 -430 {lab=dummypbias}
N -2190 10 -2150 10 {lab=ref_sel_coarse}
N -2190 50 -2150 50 {lab=ref_sel_fine}
N 420 -90 420 -40 {lab=avss}
N -30 -90 -30 -40 {lab=avss}
N 420 -490 420 -400 {lab=avdd}
N -530 -490 -530 -410 {lab=avdd}
N -530 -90 -530 -40 {lab=avss}
N -950 -440 -950 -410 {
lab=avdd}
N -970 -90 -970 -40 {lab=avss}
N -920 -1300 -140 -1300 {
lab=avdd}
N -700 -1140 -700 -1110 {lab=pbias}
N -700 -1140 -500 -1140 {lab=pbias}
N -700 -1250 -700 -1140 {lab=pbias}
N -170 -1100 -170 -990 {lab=vfb}
N -200 -1210 -170 -1210 {lab=vfb}
N -200 -1100 -170 -1100 {lab=vfb}
N -170 -1210 -170 -1100 {lab=vfb}
N -200 -1140 -140 -1140 {lab=avdd}
N -200 -1250 -140 -1250 {lab=avdd}
N -140 -1280 -140 -1250 {lab=avdd}
N -950 -490 -690 -490 {
lab=avdd}
N -690 -490 -690 -440 {lab=avdd}
N -710 -450 -710 -440 {lab=pbias}
N -1280 -450 -710 -450 {
lab=pbias}
N 50 -470 320 -470 {lab=pcasc}
N 250 -450 320 -450 {lab=pbias}
N 250 -450 250 -430 {lab=pbias}
N -330 -450 250 -450 {lab=pbias}
N -30 -490 270 -490 {lab=avdd}
N 270 -490 270 -430 {lab=avdd}
N -140 -1170 -140 -1140 {lab=avdd}
N -140 -1060 -140 -1030 {lab=avdd}
N -30 -430 -30 -400 {
lab=avdd}
N 250 -90 420 -90 {lab=avss}
N 420 -120 420 -90 {lab=avss}
N 80 -80 160 -80 {lab=nbias}
N 100 -60 160 -60 {lab=ncasc}
N -180 -90 -30 -90 {lab=avss}
N -30 -120 -30 -90 {lab=avss}
N -680 -90 -530 -90 {lab=avss}
N -530 -120 -530 -90 {lab=avss}
N -1110 -440 -950 -440 {lab=avdd}
N -950 -490 -950 -440 {
lab=avdd}
N -1120 -90 -970 -90 {lab=avss}
N -970 -120 -970 -90 {lab=avss}
N -160 -430 -30 -430 {lab=avdd}
N -30 -490 -30 -430 {
lab=avdd}
N -230 -430 -180 -430 {lab=shld2}
N -920 -1300 -920 -1160 {lab=avdd}
N -1070 -1300 -920 -1300 {
lab=avdd}
N -330 -1060 -140 -1060 {lab=avdd}
N -140 -1140 -140 -1060 {lab=avdd}
N -330 -1170 -140 -1170 {lab=avdd}
N -140 -1250 -140 -1170 {lab=avdd}
N -330 -1280 -140 -1280 {lab=avdd}
N -140 -1300 -140 -1280 {lab=avdd}
N -390 -1280 -350 -1280 {lab=shld2}
N -390 -1170 -350 -1170 {lab=shld2}
N -390 -1060 -350 -1060 {lab=shld2}
N -420 -580 -370 -580 {lab=shld2}
C {devices/ipin.sym} -420 -410 0 0 {name=p38 lab=ref_in}
C {sg13cmos5l_pr/rhigh.sym} -420 -350 0 1 {name=R4
l=138.57u
w=0.5u
body=avss
model=rhigh
spiceprefix=X
m=1}
C {devices/iopin.sym} -1330 -40 0 1 {name=p39 lab=avss}
C {devices/ipin.sym} -2550 -550 0 0 {name=p40 lab=ref_sel_vbg}
C {bias_nstack.sym} -1120 -140 0 0 {name=x4}
C {devices/iopin.sym} -1370 -490 0 1 {name=p42 lab=avdd}
C {bias_pstack.sym} -180 -360 0 0 {name=x13[1:0]}
C {bias_nstack.sym} -180 -140 0 0 {name=x17[1:0]}
C {devices/lab_wire.sym} -390 -80 0 0 {name=p43 sig_type=std_logic lab=nbias}
C {devices/lab_wire.sym} -450 -450 0 0 {name=p44 sig_type=std_logic lab=pbias}
C {devices/lab_wire.sym} -450 -470 0 0 {name=p45 sig_type=std_logic lab=pcasc}
C {devices/ipin.sym} -2550 -390 0 0 {name=p46 lab=ena_src_test0}
C {devices/ipin.sym} -2550 -320 0 0 {name=p47 lab=ena_snk_test0}
C {devices/iopin.sym} -30 -280 0 1 {name=p48 lab=src_test0}
C {devices/iopin.sym} -30 -200 0 1 {name=p49 lab=snk_test0}
C {level_shift.sym} -2010 -580 0 0 {name=x1 vdd=avdd vss=avss }
C {devices/lab_pin.sym} -1830 -620 0 1 {name=p6 sig_type=std_logic lab=enb_vbg_3v3}
C {devices/lab_pin.sym} -330 -210 0 1 {name=p8 sig_type=std_logic lab=ena_test0_3v3}
C {devices/lab_pin.sym} -330 -300 0 1 {name=p9 sig_type=std_logic lab=enb_test0_3v3}
C {level_shift.sym} -2130 -280 0 0 {name=x11 vdd=avdd vss=avss }
C {level_shift.sym} -2130 -350 0 0 {name=x23 vdd=avdd vss=avss lab=enb}
C {devices/lab_pin.sym} -1830 -320 0 1 {name=p26 sig_type=std_logic lab=ena_test0_3v3}
C {devices/lab_pin.sym} -1830 -390 0 1 {name=p27 sig_type=std_logic lab=enb_test0_3v3}
C {sg13cmos5l_stdcells/sg13cmos5l_inv_2.sym} -2450 -480 0 0 {name=x24 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_inv_2.sym} -2330 -550 0 0 {name=x35 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_pr/rhigh.sym} -170 -820 0 1 {name=R1
l=337.14u
w=0.5u
body=avss
model=rhigh
spiceprefix=X
m=1}
C {devices/ipin.sym} -1290 -1150 0 0 {name=p3 lab=vbg}
C {devices/lab_pin.sym} -1070 -1300 0 0 {name=p87 sig_type=std_logic lab=avdd}
C {devices/lab_pin.sym} -1290 -730 0 0 {name=p88 sig_type=std_logic lab=avss}
C {devices/lab_pin.sym} -1070 -900 0 0 {name=p89 sig_type=std_logic lab=nbias}
C {devices/lab_pin.sym} -560 -1120 0 0 {name=p90 sig_type=std_logic lab=pcasc}
C {devices/lab_pin.sym} -560 -1100 0 0 {name=p92 sig_type=std_logic lab=enb_std_3v3}
C {devices/ipin.sym} -2550 -480 0 0 {name=p93 lab=ena}
C {level_shift.sym} -2130 -440 0 0 {name=x36 vdd=avdd vss=avss }
C {devices/lab_pin.sym} -1080 -1110 0 0 {name=p97 sig_type=std_logic lab=ena_vbg_3v3}
C {devices/iopin.sym} -1340 -660 0 1 {name=p98 lab=dvdd}
C {devices/iopin.sym} -1340 -630 0 1 {name=p99 lab=dvss}
C {devices/lab_pin.sym} -1300 -660 0 1 {name=p1 sig_type=std_logic lab=dvdd}
C {devices/lab_pin.sym} -1300 -630 0 1 {name=p2 sig_type=std_logic lab=dvss}
C {devices/ammeter.sym} -170 -910 0 1 {name=Vmeas savecurrent=true lvs_ignore=short}
C {bias_pstack.sym} -350 -1100 0 0 {name=x19[2:0]}
C {devices/lab_pin.sym} -170 -730 0 1 {name=p101 sig_type=std_logic lab=avss}
C {devices/lab_pin.sym} -1040 -1020 0 1 {name=p105 sig_type=std_logic lab=vfb}
C {devices/lab_wire.sym} -750 -1110 0 1 {name=p100 sig_type=std_logic lab=pbias
}
C {devices/lab_pin.sym} 1940 -2300 0 0 {name=p109 sig_type=std_logic lab=vbg}
C {devices/lab_pin.sym} -1380 -370 0 0 {name=p7 sig_type=std_logic lab=ena_vbg_3v3}
C {devices/opin.sym} 320 -470 0 0 {name=p10 lab=pcasc}
C {devices/opin.sym} 320 -450 0 0 {name=p11 lab=pbias}
C {devices/opin.sym} 160 -80 0 0 {name=p12 lab=nbias}
C {devices/lab_pin.sym} -1830 -480 0 1 {name=p13 sig_type=std_logic lab=ena_3v3}
C {sg13cmos5l_stdcells/sg13cmos5l_decap_4.sym} -2060 -220 0 0 {name=x5[6:0] VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_antennanp.sym} -2060 -150 0 0 {name=x5 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {devices/lab_pin.sym} -2190 -150 0 0 {name=p14 sig_type=std_logic lab=ref_sel_vbg}
C {sg13cmos5l_stdcells/sg13cmos5l_antennanp.sym} -2060 -110 0 0 {name=x6 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_antennanp.sym} -2060 -70 0 0 {name=x7 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_antennanp.sym} -2060 -30 0 0 {name=x8 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {devices/lab_pin.sym} -2190 -110 0 0 {name=p15 sig_type=std_logic lab=ena}
C {devices/lab_pin.sym} -2190 -70 0 0 {name=p16 sig_type=std_logic lab=ena_src_test0}
C {devices/lab_pin.sym} -2190 -30 0 0 {name=p17 sig_type=std_logic lab=ena_snk_test0}
C {capa.sym} -830 -1040 0 0 {name=C2
m=1
value=225f
footprint=1206
device="ceramic capacitor"}
C {sg13cmos5l_stdcells/sg13cmos5l_inv_2.sym} -2450 -390 0 0 {name=x9 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_inv_2.sym} -2450 -320 0 0 {name=x10 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {level_shift.sym} -2010 -510 0 0 {name=x12 vdd=avdd vss=avss }
C {devices/lab_pin.sym} -1830 -550 0 1 {name=p5 sig_type=std_logic lab=ena_vbg_3v3}
C {devices/opin.sym} 160 -60 0 0 {name=p18 lab=ncasc}
C {bias_nset.sym} -680 -140 0 0 {name=x1[15:0]}
C {bias_pset.sym} -1130 -370 0 0 {name=x14}
C {devices/ammeter.sym} -420 -250 0 1 {name=Vmeas1 savecurrent=true lvs_ignore=short}
C {devices/ammeter.sym} -930 -270 0 1 {name=Vmeas2 savecurrent=true lvs_ignore=short}
C {devices/lab_pin.sym} -850 -280 0 1 {name=p19 sig_type=std_logic lab=enb_vbg_3v3}
C {devices/lab_pin.sym} -840 -220 0 1 {name=p20 sig_type=std_logic lab=ena_3v3}
C {devices/lab_pin.sym} -1330 -160 0 0 {name=p4 sig_type=std_logic lab=ena_3v3}
C {bias_amp_large.sym} -860 -1110 0 0 {name=x3}
C {bias_pstack.sym} -350 -1210 0 0 {name=x2[15:0]}
C {devices/lab_pin.sym} -560 -1230 0 0 {name=p21 sig_type=std_logic lab=pcasc}
C {devices/lab_pin.sym} -560 -1210 0 0 {name=p22 sig_type=std_logic lab=enb_fine_3v3}
C {devices/ipin.sym} -2550 -810 0 0 {name=p23 lab=ref_sel_fine}
C {level_shift.sym} -1770 -770 0 0 {name=x15 vdd=avdd vss=avss }
C {sg13cmos5l_stdcells/sg13cmos5l_inv_2.sym} -2040 -810 0 0 {name=x16 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_nand2_1.sym} -2420 -910 0 0 {name=x17 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {devices/lab_pin.sym} -1750 -810 0 1 {name=p24 sig_type=std_logic lab=enb_fine_3v3}
C {bias_pstack.sym} -350 -990 0 0 {name=x13}
C {devices/lab_pin.sym} -560 -1010 0 0 {name=p25 sig_type=std_logic lab=pcasc}
C {devices/lab_pin.sym} -560 -990 0 0 {name=p28 sig_type=std_logic lab=enb_coarse_3v3}
C {sg13cmos5l_stdcells/sg13cmos5l_nor2_1.sym} -2320 -830 0 0 {name=x18 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {devices/ipin.sym} -2550 -930 0 0 {name=p29 lab=ref_sel_coarse}
C {level_shift.sym} -1770 -870 0 0 {name=x19 vdd=avdd vss=avss }
C {sg13cmos5l_stdcells/sg13cmos5l_inv_2.sym} -2040 -910 0 0 {name=x20 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {devices/lab_pin.sym} -1750 -910 0 1 {name=p30 sig_type=std_logic lab=enb_coarse_3v3}
C {devices/lab_pin.sym} -1750 -710 0 1 {name=p31 sig_type=std_logic lab=enb_std_3v3}
C {level_shift.sym} -1770 -670 0 0 {name=x21 vdd=avdd vss=avss }
C {sg13cmos5l_stdcells/sg13cmos5l_inv_2.sym} -2040 -710 0 0 {name=x22 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_nand2_1.sym} -2160 -910 0 0 {name=x25 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_nand2_1.sym} -2160 -810 0 0 {name=x26 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_nand2_1.sym} -2160 -710 0 0 {name=x27 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_inv_2.sym} -2450 -810 0 0 {name=x29 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_nand2_1.sym} -2340 -730 0 0 {name=x28 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {lab_pin.sym} -880 -440 0 1 {name=p32 sig_type=std_logic lab=dummypbias}
C {lab_pin.sym} 70 -160 0 0 {name=p33 sig_type=std_logic lab=avss}
C {lab_pin.sym} 70 -360 0 0 {name=p34 sig_type=std_logic lab=avdd}
C {lab_pin.sym} 100 -430 0 1 {name=p35 sig_type=std_logic lab=dummypbias}
C {bias_pset2.sym} -710 -370 0 0 {name=x30}
C {sg13cmos5l_stdcells/sg13cmos5l_antennanp.sym} -2060 10 0 0 {name=x2 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_antennanp.sym} -2060 50 0 0 {name=x31 VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {devices/lab_pin.sym} -2190 10 0 0 {name=p36 sig_type=std_logic lab=ref_sel_coarse}
C {devices/lab_pin.sym} -2190 50 0 0 {name=p37 sig_type=std_logic lab=ref_sel_fine}
C {lab_pin.sym} 430 -360 0 1 {name=p41 sig_type=std_logic lab=vfb}
C {lab_pin.sym} -420 -160 0 1 {name=p50 sig_type=std_logic lab=nset}
C {lab_pin.sym} 440 -160 0 1 {name=p51 sig_type=std_logic lab=nset}
C {bias_pstack.sym} 250 -360 0 0 {name=x4[1:0]}
C {bias_nstack.sym} 250 -140 0 0 {name=x3[1:0]}
C {lab_pin.sym} -390 -1280 0 0 {name=p52 sig_type=std_logic lab=shld2}
C {lab_pin.sym} -390 -1170 0 0 {name=p53 sig_type=std_logic lab=shld2}
C {lab_pin.sym} -390 -1060 0 0 {name=p54 sig_type=std_logic lab=shld2}
C {lab_pin.sym} -230 -430 0 0 {name=p55 sig_type=std_logic lab=shld2}
C {devices/iopin.sym} -420 -580 0 1 {name=p56 lab=shld2}
C {lab_pin.sym} -370 -580 0 1 {name=p57 sig_type=std_logic lab=shld2}
