v {xschem version=3.4.6 file_version=1.2}
G {}
K {}
V {}
S {}
E {}
T {Each bias_nstack is a 250nA unit current sink, and each bias_pstack is a 250nA unit current source.
Any bias current back-end can be generated by wiring together unit sources and/or sinks.
This subcircuit combines 8 enable bits for a current DAC of 250nA to 63.75uA, one source and one sink output.} -2320 -210 0 0 0.4 0.4 {}
T {Bias generator back-end for sg13cmos5l_ocd_openframe} -2320 -280 0 0 0.6 0.6 {}
N -2190 550 -2150 550 {
lab=dvdd}
N -2190 580 -2150 580 {
lab=dvss}
N -1680 170 -1630 170 {
lab=source_ena_b_3v3[7:0]}
N -2010 190 -1980 190 {lab=source_ena[7:0]}
N -2190 510 -2150 510 {lab=avss}
N -2190 360 -2150 360 {lab=pbias}
N -2190 340 -2150 340 {lab=pcasc}
N -2190 480 -2150 480 {lab=avdd}
N -720 480 -580 480 {lab=source_ibias}
N -720 440 -680 440 {lab=avdd}
N -1050 460 -1020 460 {lab=pcasc}
N -1090 480 -1020 480 {lab=source_ena_b_3v3[0]}
N -1070 440 -1020 440 {lab=pbias}
N -720 400 -580 400 {lab=source_ibias}
N -720 360 -680 360 {lab=avdd}
N -1090 400 -1020 400 {lab=source_ena_b_3v3[1]}
N -720 320 -580 320 {lab=source_ibias}
N -720 280 -680 280 {lab=avdd}
N -1090 320 -1020 320 {lab=source_ena_b_3v3[2]}
N -720 200 -680 200 {lab=avdd}
N -1090 240 -1020 240 {lab=source_ena_b_3v3[3]}
N -720 160 -580 160 {lab=source_ibias}
N -720 120 -680 120 {lab=avdd}
N -1090 160 -1020 160 {lab=source_ena_b_3v3[4]}
N -580 400 -580 480 {lab=source_ibias}
N -580 320 -580 400 {lab=source_ibias}
N -580 240 -580 320 {lab=source_ibias}
N -720 240 -580 240 {lab=source_ibias}
N -580 160 -580 240 {lab=source_ibias}
N -1050 380 -1050 460 {lab=pcasc}
N -1070 360 -1070 440 {lab=pbias}
N -1050 380 -1020 380 {lab=pcasc}
N -1050 300 -1050 380 {lab=pcasc}
N -1050 300 -1020 300 {lab=pcasc}
N -1050 220 -1050 300 {lab=pcasc}
N -1050 220 -1020 220 {lab=pcasc}
N -1050 140 -1050 220 {lab=pcasc}
N -1050 140 -1020 140 {lab=pcasc}
N -1070 360 -1020 360 {lab=pbias}
N -1070 280 -1070 360 {lab=pbias}
N -1070 280 -1020 280 {lab=pbias}
N -1070 200 -1070 280 {lab=pbias}
N -1070 200 -1020 200 {lab=pbias}
N -1070 120 -1070 200 {lab=pbias}
N -1070 120 -1020 120 {lab=pbias}
N -1900 190 -1830 190 {lab=#net1}
N -1980 150 -1980 190 {lab=source_ena[7:0]}
N -1980 150 -1830 150 {lab=source_ena[7:0]}
N -1830 150 -1830 170 {lab=source_ena[7:0]}
N -680 360 -680 440 {lab=avdd}
N -680 280 -680 360 {lab=avdd}
N -680 200 -680 280 {lab=avdd}
N -680 120 -680 200 {lab=avdd}
N -1980 190 -1980 250 {lab=source_ena[7:0]}
N -680 40 -680 120 {lab=avdd}
N -720 -120 -680 -120 {lab=avdd}
N -720 -40 -680 -40 {lab=avdd}
N -680 -120 -680 -40 {lab=avdd}
N -720 40 -680 40 {lab=avdd}
N -680 -40 -680 40 {lab=avdd}
N -580 80 -580 160 {lab=source_ibias}
N -720 -80 -580 -80 {lab=source_ibias}
N -720 -0 -580 -0 {lab=source_ibias}
N -580 -80 -580 -0 {lab=source_ibias}
N -720 80 -580 80 {lab=source_ibias}
N -580 -0 -580 80 {lab=source_ibias}
N -680 -210 -680 -120 {lab=avdd}
N -1070 40 -1070 120 {lab=pbias}
N -1050 60 -1050 140 {lab=pcasc}
N -1090 80 -1020 80 {lab=source_ena_b_3v3[5]}
N -1090 0 -1020 0 {lab=source_ena_b_3v3[6]}
N -1090 -80 -1020 -80 {lab=source_ena_b_3v3[7]}
N -1050 60 -1020 60 {lab=pcasc}
N -1050 -20 -1050 60 {lab=pcasc}
N -1070 40 -1020 40 {lab=pbias}
N -1070 -40 -1070 40 {lab=pbias}
N -1050 -20 -1020 -20 {lab=pcasc}
N -1050 -100 -1050 -20 {lab=pcasc}
N -1070 -40 -1020 -40 {lab=pbias}
N -1070 -120 -1070 -40 {lab=pbias}
N -1050 -100 -1020 -100 {lab=pcasc}
N -1050 -210 -1050 -100 {lab=pcasc}
N -1070 -120 -1020 -120 {lab=pbias}
N -1070 -210 -1070 -120 {lab=pbias}
C {devices/iopin.sym} -2190 510 0 1 {name=p39 lab=avss}
C {devices/iopin.sym} -2190 480 0 1 {name=p42 lab=avdd}
C {devices/iopin.sym} -2190 550 0 1 {name=p98 lab=dvdd}
C {devices/iopin.sym} -2190 580 0 1 {name=p99 lab=dvss}
C {devices/lab_pin.sym} -2150 550 0 1 {name=p1 sig_type=std_logic lab=dvdd}
C {devices/lab_pin.sym} -2150 580 0 1 {name=p2 sig_type=std_logic lab=dvss}
C {devices/ipin.sym} -2190 340 0 0 {name=p3 lab=pcasc}
C {devices/ipin.sym} -2190 360 0 0 {name=p4 lab=pbias}
C {devices/ipin.sym} -2010 190 0 0 {name=p8 lab=source_ena[7:0]}
C {level_shift.sym} -1680 210 0 0 {name=x9[7:0] vdd=avdd vss=avss }
C {sg13cmos5l_stdcells/sg13cmos5l_inv_2.sym} -1940 190 0 0 {name=x46[7:0] VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_decap_4.sym} -1920 90 0 0 {name=x23[7:0] VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_antennanp.sym} -1890 250 0 0 {name=x78[7:0] VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {lab_pin.sym} -2150 510 0 1 {name=p9 sig_type=std_logic lab=avss}
C {lab_pin.sym} -2150 480 0 1 {name=p41 sig_type=std_logic lab=avdd}
C {lab_pin.sym} -2150 360 0 1 {name=p43 sig_type=std_logic lab=pbias}
C {lab_pin.sym} -2150 340 0 1 {name=p44 sig_type=std_logic lab=pcasc}
C {bias_pstack.sym} -870 480 0 0 {name=x9}
C {devices/iopin.sym} -580 160 0 0 {name=p45 lab=source_ibias}
C {lab_pin.sym} -1070 -210 1 0 {name=p47 sig_type=std_logic lab=pbias}
C {lab_pin.sym} -1050 -210 1 0 {name=p48 sig_type=std_logic lab=pcasc}
C {bias_pstack.sym} -870 400 0 0 {name=x10[1:0]}
C {bias_pstack.sym} -870 320 0 0 {name=x1[3:0]}
C {bias_pstack.sym} -870 240 0 0 {name=x2[7:0]}
C {bias_pstack.sym} -870 160 0 0 {name=x3[15:0]}
C {lab_pin.sym} -680 -210 3 1 {name=p27 sig_type=std_logic lab=avdd}
C {lab_wire.sym} -1090 160 0 0 {name=p10 sig_type=std_logic lab=source_ena_b_3v3[4]}
C {lab_wire.sym} -1090 240 0 0 {name=p11 sig_type=std_logic lab=source_ena_b_3v3[3]}
C {lab_wire.sym} -1090 320 0 0 {name=p14 sig_type=std_logic lab=source_ena_b_3v3[2]}
C {lab_wire.sym} -1090 400 0 0 {name=p15 sig_type=std_logic lab=source_ena_b_3v3[1]}
C {lab_wire.sym} -1090 480 0 0 {name=p16 sig_type=std_logic lab=source_ena_b_3v3[0]}
C {lab_pin.sym} -1630 170 0 1 {name=p18 sig_type=std_logic lab=source_ena_b_3v3[7:0]}
C {bias_pstack.sym} -870 80 0 0 {name=x12[31:0]}
C {bias_pstack.sym} -870 0 0 0 {name=x13[63:0]}
C {bias_pstack.sym} -870 -80 0 0 {name=x14[127:0]}
C {lab_wire.sym} -1090 80 0 0 {name=p19 sig_type=std_logic lab=source_ena_b_3v3[5]}
C {lab_wire.sym} -1090 0 0 0 {name=p20 sig_type=std_logic lab=source_ena_b_3v3[6]}
C {lab_wire.sym} -1090 -80 0 0 {name=p21 sig_type=std_logic lab=source_ena_b_3v3[7]}
