v {xschem version=3.4.6 file_version=1.2}
G {}
K {}
V {}
S {}
E {}
T {Each bias_nstack is a 250nA unit current sink, and each bias_pstack is a 250nA unit current source.
Any bias current back-end can be generated by wiring together unit sources and/or sinks.
This subcircuit combines 5 enable bits for a small current DAC of 250nA to 7.75uA, one source and one sink output.} -2310 -160 0 0 0.4 0.4 {}
T {Bias generator back-end for sg13cmos5l_ocd_openframe} -2310 -240 0 0 0.6 0.6 {}
N -2190 550 -2150 550 {
lab=dvdd}
N -2190 580 -2150 580 {
lab=dvss}
N -1680 170 -1630 170 {
lab=source_ena_b_3v3[4:0]}
N -2010 190 -1980 190 {lab=source_ena[4:0]}
N -2190 510 -2150 510 {lab=avss}
N -2190 360 -2150 360 {lab=pbias}
N -2190 340 -2150 340 {lab=pcasc}
N -2190 480 -2150 480 {lab=avdd}
N -1050 560 -910 560 {lab=source_ibias}
N -1050 520 -1010 520 {lab=avdd}
N -1380 540 -1350 540 {lab=pcasc}
N -1420 560 -1350 560 {lab=source_ena_b_3v3[0]}
N -1400 520 -1350 520 {lab=pbias}
N -1050 480 -910 480 {lab=source_ibias}
N -1050 440 -1010 440 {lab=avdd}
N -1420 480 -1350 480 {lab=source_ena_b_3v3[1]}
N -1050 400 -910 400 {lab=source_ibias}
N -1050 360 -1010 360 {lab=avdd}
N -1420 400 -1350 400 {lab=source_ena_b_3v3[2]}
N -1050 280 -1010 280 {lab=avdd}
N -1420 320 -1350 320 {lab=source_ena_b_3v3[3]}
N -1050 240 -910 240 {lab=source_ibias}
N -1050 200 -1010 200 {lab=avdd}
N -1420 240 -1350 240 {lab=source_ena_b_3v3[4]}
N -910 480 -910 560 {lab=source_ibias}
N -910 400 -910 480 {lab=source_ibias}
N -910 320 -910 400 {lab=source_ibias}
N -1050 320 -910 320 {lab=source_ibias}
N -910 240 -910 320 {lab=source_ibias}
N -1380 460 -1380 540 {lab=pcasc}
N -1400 440 -1400 520 {lab=pbias}
N -1380 460 -1350 460 {lab=pcasc}
N -1380 380 -1380 460 {lab=pcasc}
N -1380 380 -1350 380 {lab=pcasc}
N -1380 300 -1380 380 {lab=pcasc}
N -1380 300 -1350 300 {lab=pcasc}
N -1380 220 -1380 300 {lab=pcasc}
N -1380 220 -1350 220 {lab=pcasc}
N -1380 150 -1380 220 {lab=pcasc}
N -1400 440 -1350 440 {lab=pbias}
N -1400 360 -1400 440 {lab=pbias}
N -1400 360 -1350 360 {lab=pbias}
N -1400 280 -1400 360 {lab=pbias}
N -1400 280 -1350 280 {lab=pbias}
N -1400 200 -1400 280 {lab=pbias}
N -1400 200 -1350 200 {lab=pbias}
N -1400 150 -1400 200 {lab=pbias}
N -1900 190 -1830 190 {lab=#net1}
N -1980 150 -1980 190 {lab=source_ena[4:0]}
N -1980 150 -1830 150 {lab=source_ena[4:0]}
N -1830 150 -1830 170 {lab=source_ena[4:0]}
N -1010 440 -1010 520 {lab=avdd}
N -1010 360 -1010 440 {lab=avdd}
N -1010 280 -1010 360 {lab=avdd}
N -1010 200 -1010 280 {lab=avdd}
N -1010 150 -1010 200 {lab=avdd}
N -1980 190 -1980 250 {lab=source_ena[4:0]}
C {devices/iopin.sym} -2190 510 0 1 {name=p39 lab=avss}
C {devices/iopin.sym} -2190 480 0 1 {name=p42 lab=avdd}
C {devices/iopin.sym} -2190 550 0 1 {name=p98 lab=dvdd}
C {devices/iopin.sym} -2190 580 0 1 {name=p99 lab=dvss}
C {devices/lab_pin.sym} -2150 550 0 1 {name=p1 sig_type=std_logic lab=dvdd}
C {devices/lab_pin.sym} -2150 580 0 1 {name=p2 sig_type=std_logic lab=dvss}
C {devices/ipin.sym} -2190 340 0 0 {name=p3 lab=pcasc}
C {devices/ipin.sym} -2190 360 0 0 {name=p4 lab=pbias}
C {devices/ipin.sym} -2010 190 0 0 {name=p8 lab=source_ena[4:0]}
C {level_shift.sym} -1680 210 0 0 {name=x9[4:0] vdd=avdd vss=avss }
C {sg13cmos5l_stdcells/sg13cmos5l_inv_2.sym} -1940 190 0 0 {name=x46[4:0] VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_decap_4.sym} -1940 430 0 0 {name=x23[4:0] VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {sg13cmos5l_stdcells/sg13cmos5l_antennanp.sym} -1890 250 0 0 {name=x78[4:0] VDD=dvdd VSS=dvss prefix=sg13cmos5l_ }
C {lab_pin.sym} -2150 510 0 1 {name=p9 sig_type=std_logic lab=avss}
C {lab_pin.sym} -2150 480 0 1 {name=p41 sig_type=std_logic lab=avdd}
C {lab_pin.sym} -2150 360 0 1 {name=p43 sig_type=std_logic lab=pbias}
C {lab_pin.sym} -2150 340 0 1 {name=p44 sig_type=std_logic lab=pcasc}
C {bias_pstack.sym} -1200 560 0 0 {name=x9}
C {devices/iopin.sym} -910 240 0 0 {name=p45 lab=source_ibias}
C {lab_pin.sym} -1400 150 1 0 {name=p47 sig_type=std_logic lab=pbias}
C {lab_pin.sym} -1380 150 1 0 {name=p48 sig_type=std_logic lab=pcasc}
C {bias_pstack.sym} -1200 480 0 0 {name=x10[1:0]}
C {bias_pstack.sym} -1200 400 0 0 {name=x1[3:0]}
C {bias_pstack.sym} -1200 320 0 0 {name=x2[7:0]}
C {bias_pstack.sym} -1200 240 0 0 {name=x3[15:0]}
C {lab_pin.sym} -1010 150 3 1 {name=p27 sig_type=std_logic lab=avdd}
C {lab_wire.sym} -1420 240 0 0 {name=p10 sig_type=std_logic lab=source_ena_b_3v3[4]}
C {lab_wire.sym} -1420 320 0 0 {name=p11 sig_type=std_logic lab=source_ena_b_3v3[3]}
C {lab_wire.sym} -1420 400 0 0 {name=p14 sig_type=std_logic lab=source_ena_b_3v3[2]}
C {lab_wire.sym} -1420 480 0 0 {name=p15 sig_type=std_logic lab=source_ena_b_3v3[1]}
C {lab_wire.sym} -1420 560 0 0 {name=p16 sig_type=std_logic lab=source_ena_b_3v3[0]}
C {lab_pin.sym} -1630 170 0 1 {name=p18 sig_type=std_logic lab=source_ena_b_3v3[4:0]}
